
package org.sinekarta.ingestion.services.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Thu Feb 26 11:18:49 CET 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "transmitLinkToSipResponse", namespace = "http://ws.service.sinekarta.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transmitLinkToSipResponse", namespace = "http://ws.service.sinekarta.org/")

public class TransmitLinkToSipResponse {

    @XmlElement(name = "return")
    private TransmissionResponse _return;

    public TransmissionResponse getReturn() {
        return this._return;
    }

    public void setReturn(TransmissionResponse new_return)  {
        this._return = new_return;
    }

}

