/**
 * Copyright 2015-2020 JENIA Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package org.sinekarta.ingestionservice.commons.service.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Thu Feb 26 11:18:49 CET 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "transmitLinkToSipResponse", namespace = "http://ws.service.sinekarta.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transmitLinkToSipResponse", namespace = "http://ws.service.sinekarta.org/")

public class TransmitLinkToSipResponse {

    @XmlElement(name = "return")
    private TransmissionResponse _return;

    public TransmissionResponse getReturn() {
        return this._return;
    }

    public void setReturn(TransmissionResponse new_return)  {
        this._return = new_return;
    }

}

