/**
 * Copyright 2015-2020 JENIA Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package org.sinekarta.ingestionservice.service.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.sinekarta.ingestionservice.mets.Mets;

/**
 * This class was generated by Apache CXF 3.0.4
 * Thu Feb 26 11:18:49 CET 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "transmitSip", namespace = "http://ws.service.sinekarta.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transmitSip", namespace = "http://ws.service.sinekarta.org/", propOrder = {"responseEndpointAddress", "sip"})

public class TransmitSip {

    @XmlElement(name = "responseEndpointAddress")
    private java.lang.String responseEndpointAddress;
    @XmlElement(name = "sip")
    private Mets sip;

    public java.lang.String getResponseEndpointAddress() {
        return this.responseEndpointAddress;
    }

    public void setResponseEndpointAddress(java.lang.String responseEndpointAddress)  {
        this.responseEndpointAddress = responseEndpointAddress;
    }

    public Mets getSip() {
        return this.sip;
    }

    public void setSip(Mets sip)  {
        this.sip = sip;
    }

}

